### ISSUE TITLE
Animebytes.tracker doesn't split $releaseTags by "|"

### ISSUE THREAD

**Issue by hiddenseeker** [autodl-community/autodl-trackers#109]
The Animebytes bot announces the torrent releaseTags separated either by "/" or by "|". 
In the tracker XML file only the onces announced with "/" are parsed/split correctly.

I added this line 
```xml
<varreplace name="$releaseTags" srcvar="$releaseTags" regex="[\|]" replace="/"/>
```
before 
```xml
<extracttags srcvar="$releaseTags" split="/">
```

that fixed it for me.

**Comment by thebigmunch** [comment]
Post examples of announces where it does that.

**Comment by hiddenseeker** [comment]
latest feed from #announce :

><@Satsuki> Taifuu no Noruda - Movie  [2015] :: Bluray | MKV | h264 | 1080p | FLAC 2.0 | RAW (UCCUSS) | Freeleech! || https://animebytes.tv/torrents.php?id=24654&torrentid=189413 || school.life, scifi || Uploaded by: Timu
<@Satsuki> Hamauzu Masashi - Typhoon Noruda Original Soundtrack  [2015] :: FLAC / Lossless / CD / Log / Cue || https://animebytes.tv/torrents2.php?id=35816&torrentid=189414 || soundtrack || Uploaded by: nstz
<@Satsuki> Kenpuu Denki Berserk - TV Series  [1997] :: DVD | MKV | h264 | 720x480 | AAC | Softsubs (Yellow-Flash) || https://animebytes.tv/torrents.php?id=143&torrentid=189415 || fantasy, horror, military, seinen, classic, tragedy, demons, violence, contemporary.fantasy, dark.fantasy, dystopia, feudal.warfare, swordplay, gore, demon, manga, action, feudalwarfare, darkfantasy || Uploaded by: kombajnbizon
<@Satsuki> Wonder Garden - ONA  [2013] :: Bluray | MKV | h264 | 1080p | FLAC 2.0 | RAW (UCCUSS) | Freeleech! || https://animebytes.tv/torrents.php?id=17807&torrentid=189416 || fantasy, music || Uploaded by: Timu
<@Satsuki> Ray - Hajimete Girls!  [2015] :: FLAC / Lossless / CD / Log / Cue || https://animebytes.tv/torrents2.php?id=35817&torrentid=189417 || pop, vocal || Uploaded by: nstz
<@Satsuki> Yamada Yutaka - Tokyo Ghoul √A EXTRA CD vol.6 "Tokyo Ghoul" Mini Soundtrack  [2015] :: FLAC / Lossless / CD / Log / Cue || https://animebytes.tv/torrents2.php?id=35818&torrentid=189418 || soundtrack || Uploaded by: nstz

**Comment by weewyum** [comment]
Can confirm hiddenseeker's solution fixed the problem for me as well. 
I performed a clean install of my seedbox on the 29th August which caused the problem. Prior to this it was fine, despite no difference in the .tracker file.
