### ISSUE TITLE
Requesting a new tracker

### ISSUE THREAD

**Issue by LelTOP** [autodl-community/autodl-trackers#116]
Hi, here is the pastebin with all the info. Hope I did everything correctly.

Tracker name - Torentday
Tracker abbreviation (if applicable) - TD
Tracker IRC server address irc.torrentday.com
Tracker IRC announce channel #td.announce
Tracker IRC announcer name TD_Announce

http://pastebin.com/C9P70Pge

2nd announce

Tracker name - Torentday
Tracker abbreviation (if applicable) - TD
Tracker IRC server address irc.torrentday.com
Tracker IRC announce channel #td.announce2
Tracker IRC announcer name SimonSays

If you need anymore info or anything, just let me know.

Thanking you in advance for all you do. Your hard work is appreciated.

**Comment by OoGuru** [comment]
A tracker file for TorrentDay has been added here: https://github.com/autodl-community/autodl-trackers/pull/119
