### ISSUE TITLE
Difference between .git download and release .zip ?

### ISSUE THREAD

**Issue by dannyti** [autodl-community/autodl-trackers#124]
There is a difference in files when we compare the autodl-trackers git master download as compared to relase .zip file - https://github.com/autodl-community/autodl-trackers/releases/download/community-v251/autodl-trackers-v251.zip

Why is it different ?

**Comment by thebigmunch** [comment]
Because one is auto-generated by GitHub to include all source files while the release archive is generated by me to just include the tracker files.
