### ISSUE TITLE
update ttn announce format

### ISSUE THREAD

**Issue by starslyr** [autodl-community/autodl-trackers#136]
<DRADIS> [Episodes] Bordertown 2016 - S01E10 [WebRip / h264 / MKV / 720p / HD] [279.85 MB - Uploader: Caprica] - http://transmithe.net/torrents.php?id=81520
<DRADIS> [Episodes] Wild Kratts - S04E06 [WebRip / x264 / MKV / 1080p / HD] [1.21 GB - Uploader: Caprica] - http://transmithe.net/torrents.php?id=81521
<DRADIS> [Episodes] Inside Amy Schumer - S04E02 [WebRip / x264 / MKV / 1080p / HD] [643.99 MB - Uploader: Caprica] - http://transmithe.net/torrents.php?id=81522
<DRADIS> [Episodes] Thronecast-Game Of Thrones The Story So Far 2016 [ [ [HDTV / x264 / MKV / 720p / HD] [1.32 GB - Uploader: Zoe] - http://transmithe.net/torrents.php?id=81525
<DRADIS> [Seasons] Dragon Ball Z - Season 1 [ [BluRay / x264 / MKV / 720p / HD] [42.56 GB - Uploader: anon ] - http://transmithe.net/torrents.php?id=81542
<DRADIS> [Episodes] Elementary - S04E22 [WebDL / h264 / MKV / 720p / HD] [1.32 GB - Uploader: Caprica] - http://transmithe.net/torrents.php?id=81543
<DRADIS> [Episodes] Elementary - S04E22 [WebDL / h264 / MKV / 1080p / HD] [1.64 GB - Uploader: Caprica] - http://transmithe.net/torrents.php?id=81544
<DRADIS> [Seasons] Mystery Science Theater 3000 - Season 4 [AVI / 480p / SD] [16.52 GB - Uploader: anon ] - http://transmithe.net/torrents.php?id=80847
<DRADIS> [Seasons] Bones - Season 01 [MKV / 720p / HD] [30.14 GB - Uploader: anon ] - http://transmithe.net/torrents.php?id=80668
<DRADIS> [Seasons] Pretty Rhythm [MP4 / 480p / SD] [7.03 GB - Uploader: anon ] - http://transmithe.net/torrents.php?id=80829

**Comment by thebigmunch** [comment]
Most of those are fine. The only ones that cause an issue are ones with random extra ['s in there. Looks more like an issue on their end, since there's no reason for those to be in there.
