### ISSUE TITLE
Add Apollo Tracker File

### ISSUE THREAD

**Issue by apollorising** [autodl-community/autodl-trackers#158]
Please add a tracker file for the new site 'Apollo'. 
Details included in the below paste;
http://pastebin.com/V6x0UAnh

**Comment by RookieKiwi** [comment]
Created Apollo.tracker as below

http://pastebin.com/ChqgQpv3

Please add to repo

**Comment by thebigmunch** [comment]
The pastebin no longer exists. And there was this Pull Request (#156) open waiting for response when you posted. Perhaps you or others could look at it.

**Comment by apollorising** [comment]
Here is a new paste, I hope this helps you: 
http://pastebin.com/nyxvG1Dm

As for the other Pull Request, I don't know anything about it. I am not too technically savvy about this stuff.
