### ISSUE TITLE
add shazbat

### ISSUE THREAD

**Issue by SirPirate** [autodl-community/autodl-trackers#160]
hello,
could you add shazbat to your tracker list?

**Comment by btaroli** [comment]
+1

- Tracker Name: Shazbat
- IRC Server: irc.shazbat.tv (SSL 6697)
- Announce Channel: #shazbat.pre
- Announcer Name: Shazbat

Just recently began accessing this channel via IRC, so no samples to offer just yet. Will update again with samples as I build up some.

**Comment by btaroli** [comment]
Shazbat PRE: Homeland.S06E01.720p.HDTV.x264-BATV
Shazbat srrdb: Homeland.S06E01.720p.HDTV.x264-BATV.mkv ~ 1,341,546,006 bytes ~ CRC32: 54A15D12
Shazbat New submit: Nashville (2012) 5x01 The Wayfaring Stranger (720p .mkv)
Shazbat PRE: Homeland.S06E01.HDTV.x264-BATV
Shazbat srrdb: Homeland.S06E01.HDTV.x264-BATV.mkv ~ 331,766,678 bytes ~ CRC32: 41C4E571
Shazbat New submit: Homeland 6x01 Fair Game (720p .mkv)
Shazbat New submit: Homeland 6x01 Fair Game (.mkv)


Given how URLs are generated for torrents, I don't believe this is enough information to do that. Could be wrong though.

**Comment by thebigmunch** [comment]
https://github.com/autodl-community/autodl-irssi/wiki/FAQ#how-do-i-get-a-new-tracker-added-to-autodl-irssi
