### ISSUE TITLE
Myanonamouse tracker announce change

### ISSUE THREAD

**Issue by dizzy1** [autodl-community/autodl-trackers#161]
Torrent announce parsing is broken. 

old: New Torrent :  dfsdfs By: dfsdf Category: ( Ebooks - Magazines/Newspapers ) Size: ( 62.06 MB ) Link: ...

new: New Torrent:  sdfdsfd By: dfsdfs Category: ( Ebooks - Magazines/Newspapers ) Size: ( 62.06 MB ) Link: ...

The space was removed between the colon and torrent. 

https://www.mam  .net/forums.php?action=viewtopic&topicid=28851&page=p206163#206163

**Comment by thebigmunch** [comment]
The tracker file was changed for that in dcaff307d37428c106b036e80939670b3edf447a back in August.
