### ISSUE TITLE
Add TorrentCrate Tracker

### ISSUE THREAD

**Issue by mitsu99** [autodl-community/autodl-trackers#179]
Please add TorrentCrate to the autodl-trackers. Details and pastebin are below:

**Tracker Name**: TorrentCrate
**Tracker Abbreviation**: TC
**Tracker IRC server address**: irc.torrentcrate.org
**Tracker IRC announce channel**: #tc.announce
**Tracker IRC announcer name**: TC_Announce
**Samples**: Included in pastebin

http://pastebin.com/5bLCfcbL

**Comment by thebigmunch** [comment]
The pastebin seems to include a full tracker file. Please just host the tracker file somewhere and post a link instead.

**Comment by mitsu99** [comment]
Link: https://www.dropbox.com/s/vsbxl7mc3p7clll/torrentcrate.tracker?dl=0

**Comment by thebigmunch** [comment]
Thanks.

**Comment by mitsu99** [comment]
Anytime, thank you! Sorry I should have done that from the beginning.

**Comment by thebigmunch** [comment]
Just an FYI, there is already a tracker file with a type of ``tc``. Is there a preference of what to change that to? ``crate`` perhaps?

**Comment by mitsu99** [comment]
Crate would be fine

**Comment by mitsu99** [comment]
I made 1 little mistake and hopefully you can fix it ... I need to fix the following:

`pasteRegex="[&amp;]torrent_pass=([\da-fA-F]{32}`

needs to be

`pasteRegex="[&amp;]torrent_pass=([\da-fA-F]{32})`

I forgot the ending ")"

**Comment by thebigmunch** [comment]
Yeah. I happened to look at something for the ruTorrent plugin and noticed it. Got a release pushed already.

**Comment by mitsu99** [comment]
Yes thank you. I should have looked over it more thoroughly because I found 1 more error:

`<var name="$torrentSize"/>` 

should be

`<var name="torrentSize"/>`

I found no more errors after this and I apologize. Still rather new at regex and XML.

**Comment by thebigmunch** [comment]
Also, you had a type with ``<parsinfo>`` instead of ``<parseinfo>``, which I fixed along with ``torrentSize`` before the first release of it : P

**Comment by ddan39** [comment]
What a cluster this tracker file is. ffs test your shit before pushing it to a repo. kthnxbye

**Comment by thebigmunch** [comment]
Lulz at saying it completely broke anything. And it would only have caused a problem for anyone that updated in a short time frame.

And welcome to being blocked, giant douchebag. Feel free to go die in a fire.
