### ISSUE TITLE
FSC tracker error

### ISSUE THREAD

**Issue by SirPirate** [autodl-community/autodl-trackers#187]
Hello,
something is wrong with FSC tracker plugin. Irssi show me error:

WARNING: FSC: Nothing announced since Thu Dec 29 19:28:01 2016

any others trackers what I use works perfect! My friend also check on fresh install rtorrent+ru+autodl and also have problems.

**Comment by thebigmunch** [comment]
What do the announces look like?

**Comment by SirPirate** [comment]
<@AnnBot> Upload: The.Americans.2013.S05E09.720p.WEB-DL.H264-FUM Cat: TV/HD-x264 Size: 888.74 MB
<@AnnBot> Details: https://xxx.net/details.php?id=252212&hit=1
<@AnnBot> Download: https://xxx.net/download.php/252212/bcbnbzusxf.torrent

regexp looks ok, maybe problem is in the another place

**Comment by thebigmunch** [comment]
The announce format has changed. so the regex is definitely not ok : P

Give this a try: https://dl.dropboxusercontent.com/s/w744wd4fndeh9qw/FSC.tracker

**Comment by SirPirate** [comment]
05:20 -!- Irssi:  ERROR:  Error downloading torrent file                                     https://funsharing.net/download.php/252374/ugzqlnxixv.torrent. Error:
          Timed out! Error: Invalid torrent file, first bytes: 'No input file
          specified.'

**Comment by SirPirate** [comment]
@thebigmunch any idea?

**Comment by thebigmunch** [comment]
Is your cookie still correct? Did they change from using cookies for the downloads on the site?

**Comment by SirPirate** [comment]
@thebigmunch cookie is ok. 

> Did they change from using cookies for the downloads on the site?
I have no idea. Is there any way to check that?

**Comment by thebigmunch** [comment]
By looking at the download URLs on the site?

**Comment by SirPirate** [comment]
Url looks like up. In cookies except uid and pass I see also hashv and sesskey
