### ISSUE TITLE
AnimeBytes sub groups

### ISSUE THREAD

**Issue by minerz029** [autodl-community/autodl-trackers#194]
AnimeBytes lets an upload be tagged by a certain subtitling group. 

    Dragon Ball Z - TV Series  [1989] :: Bluray / MKV / h264 / 720p / AAC / Softsubs (WinxBloom1980]) || https://animebytes.tv/torrents.php?id=1219&torrentid=312501 || adventure, comedy, drama, fantasy, martial.arts, scifi, shounen, super.power, classic, action, supernatural || Uploaded by: Sibuna2

It would be `Softsubs (WinxBloom1980)` in this case. Currently, it doesn't look like there's any way to filter by this. It's not in tags, that's separate, and it's not the release group either. Looking at AnimeBytes.tracker, it seems like certain strings are extracted then `$releaseTags` is discarded. Would there be a way to filter these somehow?

Thanks in advance!

**Comment by thebigmunch** [comment]
There'd only be a way to capture it if it's guaranteed to be the last member of the release tags group. I'm assuming that should be the case, but you should probably ask to make sure. If so, we can add a capture for the ``release-group`` filter option.

**Comment by minerz029** [comment]
Thanks for the reply. That is indeed the case. However, it can also be Hardsubs or RAW, and the group name can also be omitted; "Hardsubs (HorribleSubs)", "Softsubs", "RAW (VCB-Studio)", "RAW" and others are all possible.

Also, this is only for anime. Manga, light novels and games would have other formats (e.g. "Translated (Vertical)" and "Raw"), but the release group (if present) would still be last in the list. Would it be possible to extract it with `<extract srcvar="$releaseTags" optional="true">` and a regex of `.* \((.*)\)$`?

How does the `match-releases` field work currently? And there are two 'extract' elements, but one is missing the 'Uploaded by: '. Would it be possible to extract the uploader similar to the year, using `<extract srcvar="tags" optional="true">`?

I'm just wondering, is there anyway way to manually test the configs without waiting for announces to come through?

**Comment by thebigmunch** [comment]
You said an awful lot for a simple yes/no question. It seems as though the answer is no, so a capture won't be done. Using ``match-releases`` would be the way to do it.

As for the rest, the Issue Tracker is for bug reports and feature requests, not support.
