### ISSUE TITLE
Add support for #announce on irc.revolutiontt.me

### ISSUE THREAD

**Issue by pokeguylow** [autodl-community/autodl-trackers#214]
There's a new announce channel at revolutiontt for all users (irc.revolutiontt.me/announce). There's already an announce channel for revtt (#vip), however it's restricted mainly to donating users. 

#announce is is open to most of the userbase, but releases are delayed by 5 minutes.

I would be willing to implement this, but I'm not sure how to structure the changes as the new channel would be a backup option for users who can't access #vip. 

Announce sample: https://pastebin.com [slash] WsueNYZM

**Comment by thebigmunch** [comment]
Give [this](https://dl.dropboxusercontent.com/s/xquf1ijpvks8nkr/RevolutionTT.tracker) a try and let me know.
