### ISSUE TITLE
could you please add TorrentSeeds.org

### ISSUE THREAD

**Issue by tashkas1** [autodl-community/autodl-trackers#226]
network="TorrentSeeds"
serverNames="irc.torrentseeds.org"
channelNames="#announce"
announcerNames="Torrentseeds"

https://pastebin.com/YNcppTYj

**Comment by thebigmunch** [comment]
Forgot to mention that the link expired before I got the chance to look at it. So, not much I can do about this.

**Comment by tashkas1** [comment]
https://pastebin.com/V56g1i04

**Comment by tashkas1** [comment]
here is the link https://pastebin.com/V56g1i04
