### ISSUE TITLE
Add TS

### ISSUE THREAD

**Issue by netopir** [autodl-community/autodl-trackers#262]
Tracker name Torrent-Syndikat
Tracker abbreviation (if applicable) TS
Tracker IRC server address irc.torrent-syndikat.org
Tracker IRC announce channel #ts-announce
Tracker IRC announcer name Synd1c4t3

https://github.com/netopir/autodl-trackers/blob/master/trackers/TSTracker.tracker

**Comment by thebigmunch** [comment]
The domain seems to not exist anymore. If it has moved, reopen this issue with new info.
