### ISSUE TITLE
Torrentleech announce change

### ISSUE THREAD

**Issue by zdeev** [autodl-community/autodl-trackers#266]
Hi Folks,

Today TorrentLeech has updated their announce by adding a 'freeleech' tag on said torrents. The regex used in the current TorrentLeech.tracker can't handle this.
https://i.imgur.com/cU8tQoQ.png

Previous line:
New Torrent Announcement: Name:'Ultimix Mega Collection' uploaded by 'Anonymous' - https://www.torrentleech.org/torrent/1612965

New line:
New Torrent Announcement: Name:'Ultimix Mega Collection' uploaded by 'Anonymous' 'freeleech' - https://www.torrentleech.org/torrent/1612965

A small change to the regex would fix this.

**Comment by jimmy6008** [comment]
Is there a fix for this problem yet? Do we need to change anything on autodl settings?

**Comment by adampetrovic** [comment]
I have a pull request open: https://github.com/autodl-community/autodl-trackers/pull/267

You can download the file yourself and overwrite the existing Torrentleech tracker file if you don't want to wait for the PR to be merged.

**Comment by helenclarko** [comment]
This still seems to be an issue. The Freeleech toggle doesn't pick up anything.

Announce Format:
<_AnnounceBot_>: New Torrent Announcement: <TV :: BoxSets>  Name:'TORRENTNAMEGOESHERE' uploaded by 'Ayano' freeleech -  https://www.torrentleech.org/torrent/*IDNUMBERGOESHERE*
