### ISSUE TITLE
SCC SD TV not being accepted

### ISSUE THREAD

**Issue by wastingaeons** [autodl-community/autodl-trackers#66]
Hi,
Sceneaccess standard def tv is not being accepted. I've tried increasing the debug level to see if theres any useful clues as to why its not.

I also have a HD filter that has the same settings except it catches 720p just fine.

I run them as two filters to run different scripts after snatch. Any ideas?

![screen shot 2015-02-07 at 12 54 48 am](https://cloud.githubusercontent.com/assets/2839483/6091513/59dfe48e-ae64-11e4-8462-e79f7c2aaeb2.png)
![screen shot 2015-02-07 at 12 54 46 am](https://cloud.githubusercontent.com/assets/2839483/6091514/59e156d4-ae64-11e4-8549-7c5934e412f3.png)
![screen shot 2015-02-07 at 12 54 41 am](https://cloud.githubusercontent.com/assets/2839483/6091515/59e4ac9e-ae64-11e4-9a9f-aef5722e0a3f.png)

**Comment by thebigmunch** [comment]
It's not tracker-specific. You can read more about why this is [here](https://github.com/autodl-community/autodl-irssi/issues/66). I see a couple SD categories in there, so I can use those to set SD resolution. Are there any others (like for movies, etc)?

**Comment by wastingaeons** [comment]
Thanks for the info. I am a bit confused as to why the TSH tracker picks up the SD releases, since the announce output doesn't explicitly say it is SD either.

**Comment by thebigmunch** [comment]
Because TSH has SD categories that are used to set SD resolution at the request of a user as I just said I could do for SCC if you give me all the categories that are SD.

**Comment by wastingaeons** [comment]
Gotcha, I see it now sorry. SCC has TV/SD-x264 and TV/XviD Then Movies/XviD is all SD, including x264.

**Comment by thebigmunch** [comment]
Test out [this](https://dl.dropbox.com/u/20787713/SceneAccess.tracker) new tracker file. Simply overwrite the current one and then reload the trackers. It should set SD resolution for those categories.

**Comment by wastingaeons** [comment]
Thanks, works perfect.
