### ISSUE TITLE
New supported Tracker

### ISSUE THREAD

**Issue by kogoromori** [autodl-community/autodl-trackers#67]
Hi,

is it possible to add an German Tracker? Name: "tntracker.org"

**Comment by thebigmunch** [comment]
https://github.com/autodl-community/autodl-irssi/wiki/FAQ#how-do-i-get-a-new-tracker-added-to-autodl-irssi

Also, make sure that the tracker staff are ok with it being added to autodl-irssi. You can post the necessary info here or send an e-mail as described [here](https://github.com/autodl-community/autodl-trackers/blob/master/CONTRIBUTING.md#submitting-an-issue).

**Comment by thebigmunch** [comment]
Closing due to lack of response.

**Comment by knutshub** [comment]
It seems it's encouraged from the staff and they developed their own script: https://tntracker.org/TNetwork.tracker

Maybe it's time to add it here, too.
