### ISSUE TITLE
x264 tracker error

### ISSUE THREAD

**Issue by stathis95194** [autodl-community/autodl-trackers#99]
Trying to use autodl-irssi with x264 returned the following error:

ERROR: Got HTTP 302, check your cookie settings! Torrent: "Torrent Name", tracker: x264

I took it up with the tracker forum and got the following message from the tracker admin.

======
im not sure about autodl-irssi specifically. But i do know that currently you need any auto dl program to be able to incorporate your login cookies for the site. kinda like the error says, the download page needs you to be authenticated  before you can download the .torrent file.
======

Seeing that autodl-irssi only registers the passkey i think there is a problem here.

**Comment by thebigmunch** [comment]
The Issue tracker is for bugs and feature requests. Use the IRC channel for support.
